<?php

namespace test\testBundle\Repository;

/**
 * Rendez_vousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rendez_vousRepository extends \Doctrine\ORM\EntityRepository
{
}
